### ISSUE TITLE
Even though enrollment is complete for an experiment, I can't use the same experiment point

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/educational-experiment-service#94] opened 2020-12-17 18:22 UTC
See screenshot. Was working to QA a concept builder experiment, and I had made a similar one a couple months ago and enrollment was completed. When I tried to create the new experiment, I saw an error that the Experiment Site was already in use (despite the old experiment no longer running). We need a better way of handling the ability to create a new experiment using the same Experiment Site ID as a prior experiment. 
<img width="899" alt="Screen Shot 2020-12-17 at 10 04 26 AM" src="https://user-images.githubusercontent.com/65311369/102527337-f10ffd00-406a-11eb-9bf1-22cd7b5fce0f.png">

**Comment by nirmalpatel** [comment] 2021-01-04 14:29
@amurphy-cl is this now a duplicate of #95 ?

**Closed as completed** 2021-01-21 20:41 UTC
