### ISSUE TITLE
Handling of students with no group assignment

### ISSUE THREAD

**Issue by amurphy-cl** [CarnegieLearningWeb/educational-experiment-service#99] opened 2021-01-15 19:35 UTC
During UpGrade testing today, I created a new assignment and completed that assignment as a new student. Currently the experiment is at [this link](https://upgrade.qa-cli.com/home/detail/749031de-e24c-46fb-9c79-d8cdd0fcf5f4). In the process, several bugs were revealed; I'm going to describe them here in one big post but we can divide them into separate issues since there may be multiple things going on that need to be addressed in different ways.

No students were incremented in the dashboard (either as Enrolled or Excluded) despite going through the correct workspace. See screenshot. 
<img width="1272" alt="Screen Shot 2021-01-15 at 2 17 28 PM" src="https://user-images.githubusercontent.com/65311369/104768941-78b95c00-573c-11eb-97a2-a57b8277a3b9.png">
This may be because an error log showed that the student's group was set to `null`, meaning that on the CL side, MATHia didn't assign a group to the student. There were in fact 2 error logs, about 5 minutes apart, roughly corresponding to when I started and completed the workspace. If we have multiple error messages, they need a little more context to help debug (or shouldn't be duplicated).
<img width="1297" alt="Screen Shot 2021-01-15 at 10 40 02 AM" src="https://user-images.githubusercontent.com/65311369/104768773-33952a00-573c-11eb-8697-9ac7797e2fff.png">
Anyway, even if there is no group membership, UpGrade should still be including this student in the experiment because both Unit of Assignment and Consistency were set to Individual (so group is not used in this experiment). It's not clear if the student simply wasn't included (because according to the Monitored Metrics, they _were_ placed in a condition), or if the student was put in Default aka no condition. 
Additionally, if the student was placed in the "Default" condition, we should still be counting them as excluded from the experiment. 

So the bugs could be identified as follows:
1. Students not incrementing in dashboard (whether included/excluded)
2. Duplicate(?) error logs, unclear if they should be treated as different and what they mean/how they are actionable
3. UpGrade may be making decisions based on group membership even if group is not used in a given experiment (when unit & consistency is set to Individual)
4. Student _does_ appear to be associated with a condition (display condition) based on viewing the Monitored Metrics, so not sure where the failure to assign is happening
5. Students in Default condition should still be counted as Excluded on the dashboard

**Comment by jerith666** [comment] 2021-01-15 20:07
Did your student in fact experience a variant in the student app when this happened?

**Comment by amurphy-cl** [comment] 2021-01-15 20:15
Yes, it looked like they got the "display" condition, which changes the title of the workspace to **Test Dummy Section NONMASTERY VAR 2**. The other condition ("layout") changes the divider pane location. So the monitored metrics that show data in the  display condition seem correct (some of the metrics are empty but that's a pipeline issue I think and doesn't belong here).

**Comment by nirmalpatel** [comment] 2021-01-18 15:26
@amurphy-cl Generally when we setup UpGrade we check whether the assignment is working or not using this web tool that lets you directly call the backend API:

SDK client lib link:- http://upgrade-client-sdk-frontend.s3-website-us-east-1.amazonaws.com/

We showed it to M. Sandbothe in a debug meeting. Can you guys confirm the issue through the debug app? In case anyone needs some documentation, Vivek demoed it previous meeting: 

Meeting video:- https://drive.google.com/drive/u/1/folders/10cu4VxDsErqvn9DMBStz4kHmFM9BbojC

Last I remember, on our latest instance, the assignment functionality was working fine...

**Comment by amurphy-cl** [comment] 2021-01-19 18:37
We can try this but one thing I'm wondering is whether the absence of `group` is affecting assignment. And even if none are assigned, we should still see a student excluded, right?

**Comment by nirmalpatel** [comment] 2021-01-19 18:48
@amurphy-cl so @JD2455 created an experiment in our environment with Individual consistency and unit of assignment, and then he tried getting the condition without providing any group info and it worked out fine... didn't you have experiments before in the CL env where the enrollment count was increasing normally?

**Comment by amurphy-cl** [comment] 2021-01-20 16:35
We had some experiments where _excluded_ list incremented, but so far with the recent round of testing, none have been included. The issue is mainly that the failure is not transparent, especially if the logs indicating group membership was not found are not meaningful for determining errors of assignment. We need any failures of this type to be logged (ideally in the UpGrade logs) and have some context so we can try to diagnose the problem.

**Comment by jerith666** [comment] 2021-01-21 14:57
The error appears to originate from here in the code: https://github.com/CarnegieLearningWeb/educational-experiment-service/blob/c1e0814f968fe903f21fd5da9e7d2ce81133ad2f/packages/Upgrade/src/api/services/ExperimentAssignmentService.ts#L264

**Comment by SritterCL** [comment] 2021-01-26 22:24
It looks like part of the issue is that we’re logging an error within getAllExperimentConditions if *any* experiment is assigning by group and there’s no group set for the student. We should have separate messages for each experiment. If the student has no working group, then, for each experiment:
-	If the experiment assigns by group:
o	Log an error if the student has not been assigned to a condition. (return “default” for the condition and 6 for the enrollment code)
o	Log a warning if the student was previously assigned to a condition (return previously-assigned condition and enrollment code 0)
-	If the experiment assigns individually:
o	Don’t log anything (assign a condition and return enrollment code 0)

If the client specifies the working group without the general group membership, that should log a warning.

**Comment by VivekFitkariwala** [comment] 2021-04-20 18:20
@msandbothe created a [PR](https://github.com/CarnegieLearningWeb/educational-experiment-service/pull/140) for this

**Closed as completed** 2021-04-28 18:12 UTC
Labels: bug, priority: high
